### ISSUE TITLE
Trouble with setting play store service account credentials

### ISSUE THREAD

**Issue by rohan-sca** [Triple-T/gradle-play-publisher#1071]
Setup :
We wanted to create a github action to automate the process of publishing a release. 
It's insecure to put the credentials on the repository so i'v set the contents of the JSON into the repository secrets. That secret is then aliased to the github workflow's environment var ANDROID_PUBLISHER_CREDENTIALS. But it seems the plugin doesnt pick it up.

We have a github workflow with
```
env:
ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}

jobs:
  build: 
  steps:
 - name: step 1
 - name: step 2
 - name: step 3
 - name: publish
    run: ./gradlew publishReleaseBundle
```
I'v setup the github secret `ANDROID_PUBLISHER_CREDENTIALS` with contents of the JSON file.
However the CI just always returns the error 
`No credentials specified. Please read our docs for more details:`

I'v followed the doc to my understanding and am unsure of what i missed.

Using com.github.triplet.gradle:play-publisher:3.7.0
and play block in build.gradle is pretty bare bones:
```
play {
    track.set("internal")
    defaultToAppBundles.set(true)
}
```
