### ISSUE TITLE
Sample code to release from travis-ci

### ISSUE THREAD

**Issue by montao** [Triple-T/gradle-play-publisher#786]
It works to make the release from a pipeline in travis. Maybe the documentation could be more clear and/or include sample code. My release of my app did work from travis pipeline (but I am not sure how to handle the JSON API key for Google Project if it were open source). I could use environment variables in Travis in the following way.

```
plugins {
    id 'com.android.application'
    id 'com.github.triplet.play' version '2.7.2'
}
android {
    signingConfigs {
        release {
            storeFile file('./droid3k.keystore')
            storePassword System.getenv('STORE_PASSWORD') 
            keyAlias System.getenv('KEY_ALIAS') 
            keyPassword System.getenv('KEY_PASSWORD') 
        }
    }

    compileSdkVersion 29
    defaultConfig {
        applicationId "dev.android.space"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 17
        versionName "0.1.12.0d"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release 
        }
        debug {
            testCoverageEnabled true
            signingConfig signingConfigs.release
        }
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
}
play {
    serviceAccountCredentials = file("api-4206650326008333-42-420ac84260008f.json")
    defaultToAppBundles = true
    track = "production" 
}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:2.15.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    androidTestImplementation "org.mockito:mockito-core:2.15.0"
    androidTestImplementation "com.google.dexmaker:dexmaker:1.2"
    androidTestImplementation "com.google.dexmaker:dexmaker-mockito:1.2"
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
}
apply plugin: 'com.github.kt3k.coveralls'

coveralls {
    jacocoReportPath = "${buildDir}/reports/coverage/debug/report.xml"
}

tasks.coveralls {
    dependsOn 'connectedAndroidTest'
    onlyIf { System.env.'CI' }
}

```

My .travis-ci.yml is the following (not latest version of Android SDK/API but it still worked):

```
language: android
sudo: required
jdk: openjdk8

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

env:
 global:
 - ANDROID_API=25
 - EMULATOR_API=24
 - ANDROID_BUILD_TOOLS=25.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes

android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - android-$EMULATOR_API_LEVEL
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-25 # google play services
 - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
 - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL # the fix!

 licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- pwd
- ls -al
- chmod +x gradlew
- echo y | android update sdk --no-ui --all --filter "tool,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository"
- echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
- ./gradlew dependencies || true # DON'T ADD unless you are getting "Install missing components using SDK manager"
#Source: https://medium.com/@oldergod/constraint-layout-and-circleci-travis-d50342696d2

before_script:
- echo "y" | android update sdk -a --no-ui --filter android-24
- echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-24
- android list targets | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # list all targets
- echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
- emulator -avd test -no-skin -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

script:
- "./gradlew publishBundle"

```
